version: '3.3'
services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: coreschema
      MYSQL_ROOT_PASSWORD: root1root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
